CondominioWepApp/Models/ErrorHandler.cs
namespace CondominioWepApp.Models
{
	public class ErrorHandler
	{
		public string? Title { get; set; }
		public string? ErrorMessage { get; set; }
		public string? Path { get; set; }
		public string? ActionMessage { get; set; }
	}


}

CondominioWepApp/Controllers/ProfileController.cs
using CondominioWepApp.FirebaseAuth;
using CondominioWepApp.Models;
using Firebase.Storage;
using Google.Cloud.Firestore;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;

namespace CondominioWepApp.Controllers
{
    public class ProfileController : Controller
    {
        public IActionResult Index()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("userSession")))
                return RedirectToAction("Index", "Error");

            //Leemos de la sesion los datos del usuario y se lo pasamos a la vista
            ViewBag.User = JsonConvert.DeserializeObject<Models.User>(HttpContext.Session.GetString("userSession"));

            return View();
        }

        public IActionResult Details(int id)
        {
            return View();
        }

		private IActionResult GetUsers()
		{
			UsersHandler usersHandler = new UsersHandler();

			ViewBag.Users = usersHandler.GetUsersCollection().Result;

			return View("Index");
		}

		public async Task<IActionResult> uploadPhoto(IFormFile photo)
        {
            //Leemos de la sesion los datos del usuario
            Models.User? user = JsonConvert.DeserializeObject<Models.User>(HttpContext.Session.GetString("userSession"));

            //Creamos la ruta donde se va a guardar la foto en el servidor local
            string photoPath = Directory.GetCurrentDirectory() + "\\wwwroot\\" + Path.Combine("Images\\", photo.FileName);

            //Copiamos la foto en la ruta del servidor local
            using (var stream = new FileStream(photoPath, FileMode.Create))
            {
                photo.CopyTo(stream);
            }

            //Abrimos la foto de servidor local para mandarla a Firebase Storage
            var downloadUrl = string.Empty;
            using (var streamToFb = System.IO.File.OpenRead(photoPath))
            {
                //Mandamos la foto a Firebase storage y este nos reponde la URL
                downloadUrl = await new FirebaseStorage($"{FirebaseAuthHelper.firebaseAppId}.appspot.com")
                                 .Child("ProfilePhotos")
                                 .Child(photo.FileName)
                                 .PutAsync(streamToFb);
            }

            ////Subir cedula
            //private IActionResult GetInfo()
            //{
            //    ProfilesHandler profilesHandler = new ProfilesHandler();

            //    ViewBag.Profile = ProfilesHandler.GetInfoCollection().Result;

            //    return View();
            //}


            //Actualizamos en Firestore Database el campo PhotoPath con la URL que nos devolvio Firebase Storage
            FirestoreDb db = FirestoreDb.Create(FirebaseAuthHelper.firebaseAppId);
            DocumentReference docRef = db.Collection("Users").Document(user?.DocumentId);
            Dictionary<string, object> dataToUpdate = new Dictionary<string, object>
            {
                { "PhotoPath", downloadUrl },
            };
            WriteResult result = await docRef.UpdateAsync(dataToUpdate);

            //Pasamos la URl de la foto a la vista
            user.PhotoPath = downloadUrl;
            ViewBag.User = user;

            return View("Index");
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditUser(string id, string name, string email, string photopath, int role, string logo, string homecode, string phone, string placalibre, string cedula)
        {
            try
            {
                UsersHandler usersHandler = new UsersHandler();

                bool result = usersHandler.Edit(id, name, email, photopath, role, logo, homecode, phone, placalibre, cedula).Result;

                return GetUsers();
            }
            catch (FirebaseStorageException ex)
            {
                ViewBag.Error = new ErrorHandler()
                {
                    Title = ex.Message,
                    ErrorMessage = ex.InnerException?.Message,
                    ActionMessage = "Go to Home",
                    Path = "/Admin"
                };

                return View("ErrorHandler");
            }
        }

		public IActionResult Edit(string id, string name, string email, string photopath, int role, string logo, string homecode, string phone, string placalibre, string cedula)
		{

			User edited = new User
			{
				Id = id,
				Name = name,
				Email = email,
				PhotoPath = photopath,
				Role = role,
				Logo = logo,
				HomeCode = homecode,
				Phone = phone,
				PlacaLibre = placalibre,
				Cedula = cedula
			};

			ViewBag.Edited = edited;
			return View();
		}

	}
}

CondominioWepApp/Controllers/SecurityController.cs
using Firebase.Storage;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using CondominioWepApp.Models;

namespace CondominioWepApp.Controllers
{
    public class SecurityController : Controller
    {
        //Index se encarga de mostrar los condominos y seleccionarlos para trabajar en su proyecto habitacional
        public IActionResult Index()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("userSession")))
                return RedirectToAction("Index", "Error");

            ViewBag.User = JsonConvert.DeserializeObject<Models.User>(HttpContext.Session.GetString("userSession"));

            if (ViewBag.User is Models.User user)
            {
                if (user.Role != 2)
                {
                    //Redirige a la página de error si el usuario no tiene un rol válido

                    return RedirectToAction("Index", "Error");
                }

                ViewBag.Role = user.Role;
            }
            else
            {
                //Redirigir a la pagina que se selecciono

                return RedirectToAction("Index", "Admin");
            }

            return GetUsers();
        }

        public IActionResult Vehicles()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("userSession")))
                return RedirectToAction("Index", "Error");

            ViewBag.User = JsonConvert.DeserializeObject<Models.User>(HttpContext.Session.GetString("userSession"));

            if (ViewBag.User is Models.User user)
            {
                if (user.Role != 2)
                {
                    //Redirige a la página de error si el usuario no tiene un rol válido

                    return RedirectToAction("Index", "Error");
                }

                ViewBag.Role = user.Role;
            }
            else
            {
                //Redirigir a la pagina que se selecciono

                return RedirectToAction("Index", "Admin");
            }

            return GetUsers();
        }

        private IActionResult GetVisits()
        {
            VisitsHandler visitsHandler = new VisitsHandler();

            ViewBag.Visits = visitsHandler.GetVisitsCollection().Result;

            return View();
        }

        public IActionResult VisitCheck()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("userSession")))
                return RedirectToAction("Index", "Error");

            ViewBag.User = JsonConvert.DeserializeObject<Models.User>(HttpContext.Session.GetString("userSession"));

            if (ViewBag.User is Models.User user)
            {
                if (user.Role != 2)
                {
                    //Redirige a la página de error si el usuario no tiene un rol válido

                    return RedirectToAction("Index", "Error");
                }

                ViewBag.Role = user.Role;
            }
            else
            {
                //Redirigir a la pagina que se selecciono

                return RedirectToAction("Index", "Admin");
            }

            return GetVisits();
        }

        public IActionResult GetUserName()
        {


            // Leemos de la sesión los datos del usuario
            Models.User? user = JsonConvert.DeserializeObject<Models.User>(HttpContext.Session.GetString("userSession"));

            // Pasamos el nombre de usuario a la vista
            ViewBag.UserName = user?.Name;

            return View();
        }

        private IActionResult GetUsers()
        {
            UsersHandler usersHandler = new UsersHandler();

            ViewBag.Users = usersHandler.GetUsersCollection().Result;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ViewVisit(string id, string name, string email, string photopath, int role, string logo, string homecode, string phone, string placalibre, string cedula)
        {
            try
            {
                UsersHandler usersHandler = new UsersHandler();

                bool result = usersHandler.View(id, name,  email, photopath, role, logo, homecode, phone, placalibre, cedula).Result;

                return GetUsers();
            }

            catch (FirebaseStorageException ex)
            {
                ViewBag.Error = new ErrorHandler()
                {
                    Title = ex.Message,
                    ErrorMessage = ex.InnerException?.Message,
                    ActionMessage = "Go to index",
                    Path = "/Vehiculos"
                };

                return View("ErrorHandler");
            }
        }
        //View se encarga de mostrar el condomino seleccionado y mostrar las visitras creadas del mismo
        public IActionResult View(string id, string name, string email, string photopath, int role, string logo, string homecode, string phone, string placalibre, string cedula)
        {
            ViewBag.User = JsonConvert.DeserializeObject<Models.User>(HttpContext.Session.GetString("userSession"));

            User viewed = new User
             {
                Id = id,
                Name = name,
                Email = email,
                PhotoPath = photopath,
                Role = role,
                Logo = logo,
                HomeCode = homecode,
                Phone = phone,
                PlacaLibre = placalibre,
                Cedula = cedula
             };

            ViewBag.Viewed = viewed;

			//Muestra el get en la vista
			return GetVisits();
		}
    }
}

CondominioWepApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WepAppCondominio</title>

    <link rel="stylesheet" href="~/css/Home.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/zephyr.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WepAppCondominio.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/WhatsApp.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Option 1: Include in HTML -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <style>

        .dropdown:hover .btn-secondary {
            background-color: white;
            color: black;
        }

        .dropdown-menu .dropdown-item:hover {
            background-color: white;
            color: black;
        }

    </style>
</head>

<body>



    <header>

        <nav class="navbar navbar-expand-lg bg-body-tertiary" style="color: black !important">
            <div class="container-fluid">
                <a class="navbar-brand" href="#" style="color: cornflowerblue">Condiminio Escazú</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor04" aria-controls="navbarColor04" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Example single secondary button -->
                <div class="btn-group">
                    <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                        Visitas
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" asp-area="" asp-controller="Visitas" asp-action="Visitas">Administrar tus visitas</a></li>
                        <li><a class="dropdown-item" asp-area="" asp-controller="Visitas" asp-action="Index">Crear Visita</a></li>
                        <li><a class="dropdown-item" asp-area="" asp-controller="Visitas" asp-action="List">Lista de Visitas</a></li>
                    </ul>
                </div>

                <div class="collapse navbar-collapse" id="navbarColor04">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Pricing">Pricing</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                    </ul>

                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    </form>

                    <div class="dropdown" style="width: 230px;">
                        <button class="btn btn-secondary dropdown-toggle d-flex align-items-center" type="button" data-bs-toggle="dropdown" style="width: 230px;" aria-expanded="false">
                            @if (ViewBag.User != null)
                            {
                                <div class="d-flex align-items-center">
                                    <div style="width: 30px; height: 30px; overflow: hidden; margin-right: 10px;">
                                        <div class="rounded-circle overflow-hidden" style="width: 100%; height: 100%;">
                                            <img src="@ViewBag.User.PhotoPath" class="d-block" width="100%" height="100%" alt="User Image" />
                                        </div>
                                    </div>
                                    <span>@ViewBag.User.Name</span>
                                </div>
                            }
                        </button>
                        <ul class="dropdown-menu" style="width: 200px; margin-top: 10px;">
                            <li><a class="dropdown-item" asp-area="" asp-controller="Profile" asp-action="Index">Profile</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li>
                                <a class="dropdown-item" asp-controller="Login" asp-action="Logout">
                                    <ion-icon name="log-out-outline" style="font-size: 1rem; vertical-align: middle; color: black;"></ion-icon> Log Out
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebAppCondominio - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            $(".close-toast").click(function () {
                $(".toast").addClass("hidden");
            });
        });
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CondominioWepApp/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WepAppCondominio</title>

    <link rel="stylesheet" href="~/css/Home.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/zephyr.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WepAppCondominio.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/WhatsApp.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Option 1: Include in HTML -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <style>

        .dropdown:hover .btn-secondary {
            background-color: white;
            color: black;
        }

        .dropdown-menu .dropdown-item:hover {
            background-color: white;
            color: black;
        }

    </style>
</head>

<body>



    <header>

        <nav class="navbar navbar-expand-lg bg-body-tertiary" style="color: black !important">
            <div class="container-fluid">
                <a class="navbar-brand" href="#" style="color: cornflowerblue">Condiminio Escazú</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor04" aria-controls="navbarColor04" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Example single secondary button -->
                <div class="btn-group">
                    <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                        Administrador
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="Index">Administrar</a></li>
                    </ul>
                </div>

                <div class="collapse navbar-collapse" id="navbarColor04">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                    </ul>
                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    </form>

                    <div class="dropdown" style="width: 230px;">
                        <button class="btn btn-secondary dropdown-toggle d-flex align-items-center" type="button" data-bs-toggle="dropdown" style="width: 230px;" aria-expanded="false">
                            @if (ViewBag.User != null)
                            {
                                <div class="d-flex align-items-center">
                                    <div style="width: 30px; height: 30px; overflow: hidden; margin-right: 10px;">
                                        <div class="rounded-circle overflow-hidden" style="width: 100%; height: 100%;">
                                            <img src="@ViewBag.User.PhotoPath" class="d-block" width="100%" height="100%" alt="User Image" />
                                        </div>
                                    </div>
                                    <span>@ViewBag.User.Name</span>
                                </div>
                            }
                        </button>
                        <ul class="dropdown-menu" style="width: 200px; margin-top: 10px;">
                            <li><a class="dropdown-item" asp-area="" asp-controller="Profile" asp-action="Index">Profile</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li>
                                <a class="dropdown-item" asp-controller="Login" asp-action="Logout">
                                    <ion-icon name="log-out-outline" style="font-size: 1rem; vertical-align: middle; color: black;"></ion-icon> Log Out
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebAppCondominio - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            $(".close-toast").click(function () {
                $(".toast").addClass("hidden");
            });
        });
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CondominioWepApp/Views/Shared/_LayoutSecurity.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WepAppCondominio</title>

    <link rel="stylesheet" href="~/css/Home.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/zephyr.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WepAppCondominio.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/WhatsApp.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Option 1: Include in HTML -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <style>

        .dropdown:hover .btn-secondary {
            background-color: white;
            color: black;
        }

        .dropdown-menu .dropdown-item:hover {
            background-color: white;
            color: black;
        }

    </style>
</head>

<body>



    <header>

        <nav class="navbar navbar-expand-lg bg-body-tertiary" style="color: black !important">
            <div class="container-fluid">
                <a class="navbar-brand" href="#" style="color: cornflowerblue">Condiminio Escazú</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor04" aria-controls="navbarColor04" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Example single secondary button -->
                <div class="btn-group">
                    <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                        Seguridad
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" asp-area="" asp-controller="Security" asp-action="Index">Administración de Proyectos</a></li>
                        <li><a class="dropdown-item" asp-area="" asp-controller="Security" asp-action="VisitCheck">Validación de Visitas</a></li>
                        <li><a class="dropdown-item" asp-area="" asp-controller="Security" asp-action="Vehicles">Administración Placas de Vehículos</a></li>
                    </ul>
                </div>

                <div class="collapse navbar-collapse" id="navbarColor04">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Security" asp-action="Index">Home</a>
                        </li>
                    </ul>

                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    </form>

                    <div class="dropdown" style="width: 230px;">
                        <button class="btn btn-secondary dropdown-toggle d-flex align-items-center" type="button" data-bs-toggle="dropdown" style="width: 230px;" aria-expanded="false">
                            @if (ViewBag.User != null)
                            {
                                <div class="d-flex align-items-center">
                                    <div style="width: 30px; height: 30px; overflow: hidden; margin-right: 10px;">
                                        <div class="rounded-circle overflow-hidden" style="width: 100%; height: 100%;">
                                            <img src="@ViewBag.User.PhotoPath" class="d-block" width="100%" height="100%" alt="User Image" />
                                        </div>
                                    </div>
                                    <span>@ViewBag.User.Name</span>
                                </div>
                            }
                        </button>
                        <ul class="dropdown-menu" style="width: 200px; margin-top: 10px;">
                            <li><a class="dropdown-item" asp-area="" asp-controller="Profile" asp-action="Index">Profile</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li>
                                <a class="dropdown-item" asp-controller="Login" asp-action="Logout">
                                    <ion-icon name="log-out-outline" style="font-size: 1rem; vertical-align: middle; color: black;"></ion-icon> Log Out
                                </a>
                            </li>
                        </ul>
                    </div>

@*                     <div class="dropdown" style="width: 200px;">
                        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" style="width: 200px;" aria-expanded="false">
                            @if (ViewBag.User != null)
                            {
                                <div class="d-flex align-items-center">
                                    <div style="width: 30px; height: 30px; overflow: hidden; margin-right: 5px;">
                                        <div class="rounded-circle overflow-hidden" style="width: 100%; height: 100%;">
                                            <img src="@ViewBag.User.PhotoPath" class="d-block" width="100%" height="100%" alt="User Image" />
                                        </div>
                                    </div>
                                    <span>@ViewBag.User.Name</span>
                                </div>
                            }
                        </button>
                        <ul class="dropdown-menu" style="width: 200px; margin-top: 10px;">
                            <li><a class="dropdown-item" asp-area="" asp-controller="Profile" asp-action="Index">Profile</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li>
                                <a class="dropdown-item" asp-controller="Login" asp-action="Logout">
                                    <ion-icon name="log-out-outline" style="font-size: 1rem; vertical-align: middle; color: black;"></ion-icon> Log Out
                                </a>
                            </li>
                        </ul>
                    </div> *@
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebAppCondominio - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            $(".close-toast").click(function () {
                $(".toast").addClass("hidden");
            });
        });
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>